# Generated by Django 4.2.7 on 2025-07-10 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(choices=[('tdap', 'Tdap (Tetanus, Diphtheria, Pertussis)'), ('influenza', 'Influenza Vaccine'), ('covid19', 'COVID-19 Vaccine'), ('hepb_birth', 'Hepatitis B (Birth)'), ('dtap_2m', 'DTaP (2 months)'), ('hib_2m', 'Hib (2 months)'), ('pcv13_2m', 'PCV13 (2 months)'), ('ipv_2m', 'IPV (2 months)'), ('rotavirus_2m', 'Rotavirus (2 months)'), ('dtap_4m', 'DTaP (4 months)'), ('hib_4m', 'Hib (4 months)'), ('pcv13_4m', 'PCV13 (4 months)'), ('ipv_4m', 'IPV (4 months)'), ('rotavirus_4m', 'Rotavirus (4 months)'), ('dtap_6m', 'DTaP (6 months)'), ('hib_6m', 'Hib (6 months)'), ('pcv13_6m', 'PCV13 (6 months)'), ('ipv_6m', 'IPV (6 months)'), ('rotavirus_6m', 'Rotavirus (6 months)'), ('hepb_6m', 'Hepatitis B (6 months)'), ('mmr_12m', 'MMR (12 months)'), ('varicella_12m', 'Varicella (12 months)'), ('hepa_12m', 'Hepatitis A (12 months)')], max_length=20)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('not_applicable', 'Not Applicable')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mother_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.newmotherprofile')),
                ('pregnant_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pregnantwomanprofile')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
