# Generated by Django 4.2.7 on 2025-07-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vaccinationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkupprogress',
            name='blood_pressure_diastolic',
            field=models.PositiveIntegerField(blank=True, help_text='Diastolic blood pressure (bottom number)', null=True),
        ),
        migrations.AddField(
            model_name='checkupprogress',
            name='blood_pressure_systolic',
            field=models.PositiveIntegerField(blank=True, help_text='Systolic blood pressure (top number)', null=True),
        ),
        migrations.AddField(
            model_name='checkupprogress',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True),
        ),
    ]
