# Generated by Django 4.2.7 on 2025-07-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_checkupprogress_blood_pressure_diastolic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocontent',
            name='week_end',
            field=models.PositiveIntegerField(blank=True, help_text='End week for this content (1-40)', null=True),
        ),
        migrations.AddField(
            model_name='infocontent',
            name='week_start',
            field=models.PositiveIntegerField(blank=True, help_text='Start week for this content (1-40)', null=True),
        ),
    ]
