# Generated by Django 4.2.7 on 2025-07-10 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_infocontent_week_end_infocontent_week_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityHealthWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('worker_type', models.CharField(choices=[('anm', 'Auxiliary Nurse Midwife (ANM)'), ('fchv', 'Female Community Health Volunteer (FCHV)'), ('asha', 'Accredited Social Health Activist (ASHA)'), ('local_doctor', 'Local Doctor')], max_length=20)),
                ('village_district', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('years_experience', models.PositiveIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expert_type', models.CharField(choices=[('doctor', 'Medical Doctor'), ('midwife', 'Midwife'), ('nurse', 'Nurse'), ('nutritionist', 'Nutritionist'), ('psychologist', 'Psychologist'), ('anm', 'Auxiliary Nurse Midwife (ANM)'), ('fchv', 'Female Community Health Volunteer (FCHV)')], max_length=20)),
                ('qualification', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('years_experience', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='experts/')),
                ('bio', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='vaccinationrecord',
            options={},
        ),
        migrations.AddField(
            model_name='infocontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infocontent',
            name='cultural_context',
            field=models.TextField(blank=True, help_text='How this information relates to Nepali culture and traditions'),
        ),
        migrations.AddField(
            model_name='infocontent',
            name='is_culturally_sensitive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='infocontent',
            name='is_government_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infocontent',
            name='local_language_available',
            field=models.BooleanField(default=False, help_text='Available in local languages (Nepali, Maithili, etc.)'),
        ),
        migrations.AddField(
            model_name='infocontent',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infocontent',
            name='source',
            field=models.CharField(choices=[('who', 'World Health Organization (WHO)'), ('nepal_mohp', 'Nepal Ministry of Health and Population'), ('local_expert', 'Local Health Expert'), ('community', 'Community Health Worker'), ('research', 'Medical Research')], default='local_expert', max_length=20),
        ),
        migrations.AddField(
            model_name='infocontent',
            name='source_reference',
            field=models.CharField(blank=True, help_text='Specific reference or document number', max_length=500),
        ),
        migrations.AddField(
            model_name='infocontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='infocontent',
            name='category',
            field=models.CharField(choices=[('diet', 'Diet'), ('vaccine', 'Vaccine'), ('exercise', 'Exercise'), ('mental', 'Mental Health'), ('breastfeeding', 'Breastfeeding'), ('danger_signs', 'Danger Signs'), ('cultural', 'Cultural Guidance')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('story', models.TextField()),
                ('outcome', models.CharField(help_text="e.g., 'Safe delivery', 'Healthy baby', 'Recovery'", max_length=100)),
                ('village_district', models.CharField(help_text='Village and district', max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='infocontent',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.healthexpert'),
        ),
    ]
