# Generated by Django 4.2.7 on 2025-07-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_communityhealthworker_healthexpert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_type', models.CharField(choices=[('do', 'Do'), ('dont', "Don't")], max_length=5)),
                ('text_en', models.CharField(max_length=255)),
                ('text_ne', models.CharField(blank=True, max_length=255)),
                ('trimester', models.PositiveSmallIntegerField(choices=[(0, 'All'), (1, 'First Trimester'), (2, 'Second Trimester'), (3, 'Third Trimester')], default=0)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class, e.g., fa-leaf', max_length=50)),
                ('source', models.CharField(blank=True, help_text='e.g., WHO, MoHP', max_length=100)),
                ('info', models.CharField(blank=True, help_text='Extra info for tooltip', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
