# Generated by Django 4.2.7 on 2025-07-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pregnancytip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkupprogress',
            name='health_metrics',
        ),
        migrations.AddField(
            model_name='checkupprogress',
            name='child_feeding_status',
            field=models.CharField(blank=True, choices=[('breastfeeding', 'Breastfeeding'), ('formula', 'Formula Feeding'), ('mixed', 'Mixed Feeding'), ('weaning', 'Weaning')], help_text="Child's current feeding method", max_length=20),
        ),
        migrations.AddField(
            model_name='checkupprogress',
            name='child_head_circumference_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Child's head circumference in centimeters", max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='checkupprogress',
            name='child_height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Child's height in centimeters", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='checkupprogress',
            name='child_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Child's weight in kilograms", max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='checkupprogress',
            name='fever',
            field=models.BooleanField(default=False, help_text='Does mother have fever?'),
        ),
        migrations.AddField(
            model_name='checkupprogress',
            name='fever_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Fever temperature in Celsius', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='checkupprogress',
            name='blood_pressure_diastolic',
            field=models.PositiveIntegerField(blank=True, help_text="Mother's diastolic blood pressure (bottom number)", null=True),
        ),
        migrations.AlterField(
            model_name='checkupprogress',
            name='blood_pressure_systolic',
            field=models.PositiveIntegerField(blank=True, help_text="Mother's systolic blood pressure (top number)", null=True),
        ),
        migrations.AlterField(
            model_name='checkupprogress',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Mother's weight in kilograms", max_digits=5, null=True),
        ),
    ]
