# Generated by Django 4.2.7 on 2025-07-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_checkupprogress_health_metrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancytip',
            name='tip_type',
            field=models.CharField(choices=[('do', 'Do'), ('dont', "Don't"), ('important', 'Important Notice')], max_length=10),
        ),
    ]
