# Generated by Django 4.2.7 on 2025-07-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pregnancytip_tip_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Brief description of the video content')),
                ('video_url', models.URLField(help_text='YouTube, Vimeo, or direct video URL')),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('direct', 'Direct Upload'), ('other', 'Other Platform')], default='youtube', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, help_text='Video thumbnail image', null=True, upload_to='trust_videos/')),
                ('duration', models.CharField(blank=True, help_text="Video duration (e.g., '5:30')", max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this video prominently')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trust Video',
                'verbose_name_plural': 'Trust Videos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
