# Generated by Django 4.2.7 on 2025-07-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_trustvideo'),
    ]

    operations = [
        # Rename old columns to new ones
        migrations.RenameField(
            model_name='pregnancytip',
            old_name='text_en',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='pregnancytip',
            old_name='text_ne',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='pregnancytip',
            old_name='trimester',
            new_name='week_start',
        ),
        # Add missing columns
        migrations.AddField(
            model_name='pregnancytip',
            name='week_end',
            field=models.IntegerField(null=True, blank=True, help_text='Ending week of pregnancy'),
        ),
        migrations.AddField(
            model_name='pregnancytip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        # Remove old columns that are no longer needed
        migrations.RemoveField(
            model_name='pregnancytip',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='pregnancytip',
            name='source',
        ),
        migrations.RemoveField(
            model_name='pregnancytip',
            name='info',
        ),
    ]
