# Generated by Django 5.2.4 on 2025-07-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pregnancytip_week_end_default'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrustVideo',
        ),
        migrations.AlterModelOptions(
            name='pregnancytip',
            options={'ordering': ['week_start', 'created_at']},
        ),
        migrations.AddField(
            model_name='newmotherprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='pregnantwomanprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='pregnancytip',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pregnancytip',
            name='tip_type',
            field=models.CharField(choices=[('general', 'General'), ('nutrition', 'Nutrition'), ('exercise', 'Exercise'), ('safety', 'Safety'), ('emotional', 'Emotional Health'), ('medical', 'Medical')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='pregnancytip',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pregnancytip',
            name='week_end',
            field=models.IntegerField(help_text='Ending week of pregnancy'),
        ),
        migrations.AlterField(
            model_name='pregnancytip',
            name='week_start',
            field=models.IntegerField(help_text='Starting week of pregnancy'),
        ),
    ]
