# Generated by Django 5.2.4 on 2025-07-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_trustvideo_alter_pregnancytip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocontent',
            name='body_ne',
            field=models.TextField(blank=True, help_text='Body in Nepali', null=True),
        ),
        migrations.AddField(
            model_name='infocontent',
            name='title_ne',
            field=models.CharField(blank=True, help_text='Title in Nepali', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pregnancytip',
            name='content_ne',
            field=models.TextField(blank=True, help_text='Content in Nepali', null=True),
        ),
        migrations.AddField(
            model_name='pregnancytip',
            name='title_ne',
            field=models.CharField(blank=True, help_text='Title in Nepali', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usertestimonial',
            name='story_ne',
            field=models.TextField(blank=True, help_text='Story in Nepali', null=True),
        ),
        migrations.AddField(
            model_name='usertestimonial',
            name='title_ne',
            field=models.CharField(blank=True, help_text='Title in Nepali', max_length=200, null=True),
        ),
    ]
