# Generated by Django 5.2.4 on 2025-07-17 16:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_infocontent_body_ne_infocontent_title_ne_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('message', models.TextField(blank=True, help_text='The message content or error details.')),
                ('mother', models.ForeignKey(blank=True, help_text='New mother profile if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.newmotherprofile')),
                ('pregnant_woman', models.ForeignKey(blank=True, help_text='Pregnant woman profile if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pregnantwomanprofile')),
                ('user', models.ForeignKey(blank=True, help_text='The user who received the notification (if applicable).', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaccination_record', models.ForeignKey(blank=True, help_text='The vaccination record related to this notification.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vaccinationrecord')),
            ],
        ),
    ]
