# Generated by Django 4.2.7 on 2025-12-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_vaccinationnotificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocontent',
            name='postpartum_stage',
            field=models.CharField(choices=[('early', 'Early Recovery (0-6 weeks)'), ('mid', 'Mid Recovery (6 weeks - 3 months)'), ('established', 'Established (3+ months)'), ('all', 'All Stages')], default='all', help_text='Relevant postpartum stage for new mothers', max_length=20),
        ),
        migrations.AddField(
            model_name='infocontent',
            name='target_audience',
            field=models.CharField(choices=[('pregnant', 'Pregnant Women'), ('mother', 'New Mothers'), ('both', 'Both')], default='both', help_text='Target audience for this content', max_length=10),
        ),
        migrations.AddField(
            model_name='infocontent',
            name='trimester',
            field=models.CharField(choices=[('1', 'First Trimester (Weeks 1-13)'), ('2', 'Second Trimester (Weeks 14-26)'), ('3', 'Third Trimester (Weeks 27-40)'), ('all', 'All Trimesters')], default='all', help_text='Relevant trimester for pregnant women', max_length=5),
        ),
    ]
