# Generated by Django 4.2.7 on 2025-12-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_trimester_postpartum_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmotherprofile',
            name='child_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newmotherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='pregnantwomanprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='vaccinationnotificationlog',
            name='notification_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10),
        ),
    ]
