# Generated by Django 4.2.7 on 2025-12-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_newmotherprofile_child_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmotherprofile',
            name='child_name',
        ),
        migrations.RemoveField(
            model_name='newmotherprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='pregnantwomanprofile',
            name='profile_picture',
        ),
    ]
