# Generated by Django 6.0 on 2025-12-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_newmotherprofile_child_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('nutrition', 'Nutrition'), ('medicine', 'Medicine'), ('lifestyle', 'Lifestyle'), ('exercise', 'Exercise'), ('medical_attention', 'Medical Attention Required')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=10)),
                ('medicine_name', models.CharField(blank=True, max_length=100)),
                ('dosage', models.CharField(blank=True, help_text="e.g., '500mg twice daily'", max_length=100)),
                ('duration', models.CharField(blank=True, help_text="e.g., '7 days'", max_length=100)),
                ('calories_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_grams', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('iron_mg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('calcium_mg', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('action_required', models.BooleanField(default=False, help_text='Does this require immediate action?')),
                ('follow_up_days', models.PositiveIntegerField(blank=True, help_text='Days until follow-up recommended', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.checkupprogress')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
    ]
